import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#eceef0',
        'on-tertiary-fixed': '#2a1700',
        outline: '#727785',
        'inverse-primary': '#adc6ff',
        'on-background': '#191c1e',
        'tertiary-container': '#a36700',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'secondary-container': '#6cf8bb',
        'surface-dim': '#d8dadc',
        'on-secondary-fixed': '#002113',
        'primary-container': '#2170e4',
        'outline-variant': '#c2c6d6',
        'on-primary-fixed': '#001a42',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        primary: '#0058be',
        'tertiary-fixed': '#ffddb8',
        'inverse-on-surface': '#eff1f3',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed-variant': '#004395',
        surface: '#f7f9fb',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#4edea3',
        'secondary-fixed': '#6ffbbe',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#424754',
        background: '#f7f9fb',
        secondary: '#006c49',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-tint': '#005ac2',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#fefcff',
        'inverse-surface': '#2d3133',
        'on-tertiary-container': '#fffbff',
        tertiary: '#825100',
        'surface-variant': '#e0e3e5',
        'primary-fixed': '#d8e2ff',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714d',
        'primary-fixed-dim': '#adc6ff',
        'on-error': '#ffffff',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['var(--font-body)', 'Manrope', 'sans-serif'],
        label: ['var(--font-body)', 'Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '1rem',
        xl: '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [forms],
}

export default config
